baseURL: https://alohamask.org
languageCode: en-us
defaultContentLanguage: en
title: alohamask
theme: cupper-hugo-theme
googleAnalytics: UA-123456789-1
disqusShortname: yourdiscussshortname
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Bringing volunteers together to design, create, and distribute open source masks to essential workers.
  homeMetaContent: Bringing volunteers together to design, create, and distribute open source masks to essential workers.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Request Kits
      url: /requests/
      weight: 2
    - name: Volunteer
      url: /volunteering/
      weight: 3
    - name: Instructions
      url: /instructions/
      weight: 4
    - name: Other Resources
      url: /resources/
      weight: 5
    - name: About
      url: /about/
      weight: 6


markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
